/*******************************************************************************************************
* @Name         NpsServiceRequestWrapper 
* @Author       Anshul Sharma 
* @Date         03/01/2023
* @Description  This is a wrapper class to construct NPS callout request.
*******************************************************************************************/
public class NpsServiceRequestWrapper {
public String sfId;
public String orderNumber;
public String customerEmail;

}